import { hashSync } from 'bcrypt-ts-edge';

const sampleData = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: hashSync('123456', 10),
      role: 'admin',
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: hashSync('123456', 10),
      role: 'user',
    },
  ],
  products: [
    {
      name: 'Polo Sporting Stretch Shirt',
      slug: 'polo-sporting-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Classic Polo style with modern comfort',
      images: [
        'https://l5wjt4vbfy.ufs.sh/f/GwKvHFNqcOhVDzqtoGlGAxBRCqULJQfPz7jDFatN9TcbZmYe',
        'https://l5wjt4vbfy.ufs.sh/f/GwKvHFNqcOhVZgBrOtP7ZJ8iOhl4NypeWYXRAmodu2Us3trE',
      ],
      price: 59.99,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner:
        'https://l5wjt4vbfy.ufs.sh/f/GwKvHFNqcOhVmTQTrv8EWEKh9URpQqy6bG8io1nvT0jBHg5I',
    },
    {
      name: 'Brooks Brothers Long Sleeved Shirt',
      slug: 'brooks-brothers-long-sleeved-shirt',
      category: "Men's Dress Shirts",
      description: 'Timeless style and premium comfort',
      images: [
        'https://l5wjt4vbfy.ufs.sh/f/GwKvHFNqcOhVbfSkbiAQR60mSULYWKGdgMy7XB9qChkxbefI',
        'https://l5wjt4vbfy.ufs.sh/f/GwKvHFNqcOhVVG6dCUgO6NzW5TuPi9lGUAn2jQ0MI17FtpbD',
      ],
      price: 85.9,
      brand: 'Brooks Brothers',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner:
        'https://l5wjt4vbfy.ufs.sh/f/GwKvHFNqcOhVwYzqzNaHEvDJT2Mqg5r9XsIpydxal1ZNoRmW',
    },
    {
      name: 'Tommy Hilfiger Classic Fit Dress Shirt',
      slug: 'tommy-hilfiger-classic-fit-dress-shirt',
      category: "Men's Dress Shirts",
      description: 'A perfect blend of sophistication and comfort',
      images: [
        'https://l5wjt4vbfy.ufs.sh/f/GwKvHFNqcOhV9zBOYn385kcNP2u3bREtFsIgG4ynKS7wX1hv',
        'https://l5wjt4vbfy.ufs.sh/f/GwKvHFNqcOhVlNVjRJI9z1i4RKQWIusyOjwb2703ctdHVpMZ',
      ],
      price: 99.95,
      brand: 'Tommy Hilfiger',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Calvin Klein Slim Fit Stretch Shirt',
      slug: 'calvin-klein-slim-fit-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Streamlined design with flexible stretch fabric',
      images: [
        'https://l5wjt4vbfy.ufs.sh/f/GwKvHFNqcOhVqdLDEEBQmDHKL0rh4pY3OyVX69GbPxit2AeR',
        'https://l5wjt4vbfy.ufs.sh/f/GwKvHFNqcOhV7qBtTbndfQvmMKySP5Fgl1TIURYLsX4aoBb9',
      ],
      price: 39.95,
      brand: 'Calvin Klein',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Ralph Lauren Oxford Shirt',
      slug: 'polo-ralph-lauren-oxford-shirt',
      category: "Men's Dress Shirts",
      description: 'Iconic Polo design with refined oxford fabric',
      images: [
        'https://l5wjt4vbfy.ufs.sh/f/GwKvHFNqcOhVDmHHb0MlGAxBRCqULJQfPz7jDFatN9TcbZmY',
        'https://l5wjt4vbfy.ufs.sh/f/GwKvHFNqcOhVsRdGunBc8NdK4ih7tWygl5aLwAeVZxY6QnH9',
      ],
      price: 79.99,
      brand: 'Polo',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Classic Pink Hoodie',
      slug: 'polo-classic-pink-hoodie',
      category: "Men's Sweatshirts",
      description: 'Soft, stylish, and perfect for laid-back days',
      images: [
        'https://l5wjt4vbfy.ufs.sh/f/GwKvHFNqcOhVGJcvZBNqcOhVultwE2A7fQIs1WNSzryKUMRF',
        'https://l5wjt4vbfy.ufs.sh/f/GwKvHFNqcOhVndW1AvHOJiMDTke6UXZESftmy9asqvI7p01L',
      ],
      price: 99.99,
      brand: 'Polo',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
